### PR TITLE
Search engines

### PR DESCRIPTION
**Pull request by TravelingTechGuy**
1. Added support for bing and duckduckgo
2. Removed key in manifest that caused an error on extension load
3. Simplified adding more domains/search engines in the future

### CODE REVIEW

**Comment by JohnnyJumper** [comment]
Thank you a lot for your PR. It all looks good.
I will do some little changes like adding more search engines to support and having a separate manifest file for Mozilla and release updates to stores.

**Comment by TravelingTechGuy** [comment]
One thing to notice: I found out while debugging, that DuckDuckGo will search either with a `/search?q=...` path, or `/?q=...` path. So I fixed the condition looking just for `/search` in a non-ideal manner 😀 (in background.tsx).

Perhaps there's a better way to generalize these, and other search engines?

**Comment by resynth1943** [comment]
How would this work with POST? Also, have you considered supporting other engines, such as Mojeek? Qwant?

**Comment by TravelingTechGuy** [comment]
I don't think POST is handled by this extension - only GET (at least that's what in the `background.tsx` file).

Other search engines can be easily added, as long as they subscribe to `*://*.EngineName.com/*?q=SearchTerm`.

If the the pattern is different, new parsing logic is needed.

To add engines, you need to change 2 files:

1. `bacground.tsx` - add the engine to the `searchEngines` array if it supports the existing pattern, or add logic otherwise.
2. `manifest.json` - you need to ask permission to listen to URLs pointing to the engine's site.

As @JohnnyJumper suggested, it could be easy to either build a script that adds a search engine to both files with one line, or, alternatively, populate the array in `background.tsx` by reading the manifest.

**Comment by resynth1943** [comment]
Hmm. I have to be honest, I'm not sure if this [restricted model](https://github.com/unstoppabledomains/resolution-browser-extension/blob/master/src/util/searchEngines.ts) is very good. Wouldn't it be better to use regular expressions? Is that something we can do, or are we restricted by `manifest.json`?

**Comment by TravelingTechGuy** [comment]
You have to specify all sites you plan to access/inspect/affect from your extension in the manifest file. It allows users to know in advance what information is shared with an extension. It's similar to the permissions model of Android apps.

**Comment by resynth1943** [comment]
I know how the Manifest works, I was referring to the code I had linked :-)

**Comment by TravelingTechGuy** [comment]
😀
Frankly, in not in love with it either. What do you suggest?

**Comment by resynth1943** [comment]
Maybe some sort of `map[domain_name] → RegExp` system? Then the regular expression could match against the URL ...? Just a thought.

**Comment by TravelingTechGuy** [comment]
IDK - won't it just make it less readable, and harder to change in case one of the search engines changes their scheme?

As is, it's easy to read, understand, and maintain. It's just a repository of (ultimately finite) links. I think there are other things to optimize 😀

**Pull request merged**
